server:
  port: ${SERVER_PORT:8080}
spring:
  main:
    banner-mode: off
  application:
    name: CATER_WEB_BACKEND
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${DB_HOST:192.168.230.84}:${DB_PORT:5433}/${DB_SCHEMA:pd}?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: dev
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql: ERROR